# Generated by Django 4.0.3 on 2022-09-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='captcha_score',
            field=models.FloatField(default=0.0),
        ),
    ]
