# Generated by Django 4.1.1 on 2022-09-11 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Tracker',
        ),
    ]
